name: env_AutoGluon_202502
channels:
  - conda-forge
dependencies:
  - absl-py=2.1.0
  - accelerate=0.34.2
  - adagio=0.2.6
  - aiofiles=24.1.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.10.5
  - aiohttp-cors=0.7.0
  - aiosignal=1.3.2
  - alembic=1.14.1
  - altair=5.5.0
  - annotated-types=0.7.0
  - antlr-python-runtime=4.9.3
  - anyio=4.8.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=25.1.0
  - autogluon=1.2.0
  - autogluon.common=1.2.0
  - autogluon.core=1.2.0
  - autogluon.features=1.2.0
  - autogluon.multimodal=1.2.0
  - autogluon.tabular=1.2.0
  - autogluon.timeseries=1.2.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - binaryornot=0.4.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - boto3=1.36.16
  - botocore=1.36.16
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-blosc2=2.15.2
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.1
  - cairo=1.18.2
  - catalogue=2.0.10
  - catboost=1.2.7
  - certifi=2025.1.31
  - cffi=1.17.1
  - chardet=5.2.0
  - charls=2.4.2
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpathlib=0.20.0
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorful=0.5.6
  - colorlog=6.9.0
  - comm=0.2.2
  - confection=0.1.4
  - contourpy=1.3.1
  - cookiecutter=2.6.0
  - coreforecast=0.0.12
  - cpython=3.10.16
  - cryptography=44.0.0
  - cycler=0.12.1
  - cymem=2.0.11
  - cython-blis=1.0.1
  - dart-sass=1.58.3
  - dataclasses=0.8
  - datasets=2.2.1
  - dav1d=1.2.1
  - debugpy=1.8.12
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deno=1.46.3
  - deno-dom=0.1.41
  - dill=0.3.9
  - distlib=0.3.9
  - dnspython=2.7.0
  - duckdb=1.1.3
  - email-validator=2.2.0
  - email_validator=2.2.0
  - esbuild=0.24.2
  - evaluate=0.4.3
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fastai=2.7.18
  - fastapi=0.115.8
  - fastapi-cli=0.0.7
  - fastcore=1.7.20
  - fastdownload=0.0.7
  - fastexcel=0.12.1
  - fastprogress=1.0.3
  - feature_engine=1.8.3
  - ffmpeg=7.1.0
  - ffmpy=0.3.0
  - filelock=3.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fs=2.4.16
  - fsspec=2025.2.0
  - fugue=0.9.1
  - future=1.0.0
  - gdk-pixbuf=2.42.12
  - gdown=5.2.0
  - giflib=5.2.2
  - gluonts=0.16.0
  - google-api-core=2.24.1
  - google-auth=2.38.0
  - googleapis-common-protos=1.66.0
  - gradio=3.24.1
  - gradio-client=0.0.5
  - graphite2=1.3.13
  - graphviz=12.2.1
  - greenlet=3.1.1
  - grpcio=1.67.1
  - gts=0.7.6
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - htmlmin=0.1.12
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - huggingface_hub=0.28.0
  - hyperframe=6.1.0
  - hyperopt=0.2.7
  - icu=75.1
  - idna=3.10
  - imagecodecs=2024.12.30
  - imagehash=4.3.1
  - imageio=2.37.0
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.32.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - jmespath=1.0.1
  - joblib=1.4.2
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - jxrlib=1.1
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarrow=19.0.0
  - libarrow-acero=19.0.0
  - libarrow-dataset=19.0.0
  - libarrow-substrait=19.0.0
  - libavif16=1.1.1
  - libblas=3.9.0
  - libboost=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.11.1
  - libde265=1.0.15
  - libdeflate=1.23
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgd=2.3.3
  - libglib=2.82.2
  - libgoogle-cloud=2.34.0
  - libgoogle-cloud-storage=2.34.0
  - libgrpc=1.67.1
  - libheif=1.19.5
  - libhwloc=2.11.2
  - libhwy=1.1.0
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - liblightgbm=4.5.0
  - liblzma=5.6.4
  - libopus=1.3.1
  - libparquet=19.0.0
  - libpng=1.6.46
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - libsentencepiece=0.2.0
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libutf8proc=2.10.0
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lightgbm=4.5.0
  - lightning=2.5.0.post0
  - lightning-utilities=0.12.0
  - lime=0.2.0.1
  - linkify-it-py=2.0.3
  - llvmlite=0.44.0
  - lz4-c=1.10.0
  - mako=1.3.9
  - markdown=3.6
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.3.3
  - mdurl=0.1.2
  - mistune=3.1.1
  - mizani=0.13.1
  - mlforecast=0.13.4
  - model-index=0.1.11
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - multimethod=1.12
  - multiprocess=0.70.17
  - munkres=1.1.4
  - murmurhash=1.0.10
  - narwhals=1.25.2
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlpaug=1.1.11
  - nltk=3.9.1
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numba=0.61.0
  - numpy=1.26.4
  - omegaconf=2.3.0
  - opencensus=0.11.3
  - opencensus-context=0.1.3
  - opencl-headers=2024.10.24
  - openh264=2.5.0
  - openjpeg=2.5.3
  - openmim=0.3.7
  - openssl=3.4.1
  - optuna=4.2.0
  - orc=2.0.3
  - ordered-set=4.1.0
  - orjson=3.10.15
  - overrides=7.7.0
  - packaging=24.2
  - pandarallel=1.6.5
  - pandas=2.2.3
  - pandoc=3.4
  - pandocfilters=1.5.0
  - pango=1.56.1
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pdf2image=1.17.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - plotly=6.0.0
  - plotnine=0.14.5
  - poppler=24.12.0
  - poppler-data=0.4.12
  - preshed=3.0.9
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - proto-plus=1.26.0
  - protobuf=5.28.3
  - psutil=6.1.1
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - py-spy=0.4.0
  - py-xgboost=2.1.4
  - py4j=0.10.9.9
  - pyale=1.2.0
  - pyarrow=19.0.0
  - pyarrow-core=19.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pydub=0.25.1
  - pygments=2.19.1
  - pynndescent=0.5.13
  - pyopenssl=25.0.0
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - pytesseract=0.3.10
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.1
  - python-duckdb=1.1.3
  - python-fastjsonschema=2.21.1
  - python-graphviz=0.20.3
  - python-json-logger=2.0.7
  - python-multipart=0.0.20
  - python-slugify=8.0.4
  - python-tzdata=2025.1
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-lightning=2.5.0.post0
  - pytorch-metric-learning=2.3.0
  - pytz=2024.1
  - pyu2f=0.1.5
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - quarto=1.6.41
  - rav1e=0.6.6
  - ray-core=2.40.0
  - ray-default=2.40.0
  - ray-tune=2.40.0
  - re2=2024.07.02
  - referencing=0.36.2
  - regex=2024.11.6
  - requests=2.32.3
  - responses=0.18.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - rpds-py=0.22.3
  - rsa=4.9
  - s3transfer=0.11.2
  - safetensors=0.5.2
  - scikit-explain=0.1.4
  - scikit-image=0.24.0
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - sdl2=2.30.10
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - semantic_version=2.10.0
  - send2trash=1.8.3
  - sentencepiece=0.2.0
  - sentencepiece-python=0.2.0
  - sentencepiece-spm=0.2.0
  - seqeval=1.2.2
  - setproctitle=1.3.4
  - setuptools=75.8.0
  - shap=0.46.0
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.8
  - slicer=0.0.8
  - smart-open=7.1.0
  - smart_open=7.1.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - spacy=3.8.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlalchemy=2.0.38
  - srsly=2.5.1
  - stack_data=0.6.3
  - starlette=0.45.3
  - statsforecast=1.7.8
  - statsmodels=0.14.4
  - svt-av1=2.3.0
  - sympy=1.13.3
  - tabulate=0.9.0
  - tbb=2021.13.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorboardx=2.6.2.2
  - terminado=0.18.1
  - text-unidecode=1.3
  - thinc=8.3.2
  - threadpoolctl=3.5.0
  - tifffile=2025.1.10
  - timm=1.0.3
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.21.0
  - tomli=2.2.1
  - toolz=0.12.1
  - torchmetrics=1.2.1
  - torchvision=0.20.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.48.3
  - triad=0.9.8
  - typeguard=4.4.1
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - typst=0.11.0
  - tzdata=2025a
  - uc-micro-py=1.0.3
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - utilsforecast=0.2.3
  - uvicorn=0.34.0
  - uvicorn-standard=0.34.0
  - virtualenv=20.29.1
  - visions=0.7.6
  - wasabi=1.1.2
  - watchfiles=1.0.4
  - wcwidth=0.2.13
  - weasel=0.4.1
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=14.2
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wordcloud=1.9.4
  - wrapt=1.17.2
  - x264=1!164.3095
  - x265=3.5
  - xarray=2025.1.2
  - xgboost=2.1.4
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.1
  - xxhash=0.8.2
  - yaml=0.2.5
  - yarl=1.9.4
  - ydata-profiling=4.12.2
  - yellowbrick=1.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.21.0
  - zlib-ng=2.2.3
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - mljar-scikit-plot==0.3.12
      - polars==1.22.0
